require "legacy"

describe "queries" do
  let(:db) do
    Legacy.new(ENV['ORACLE_USER'], ENV['ORACLE_PASSWORD'], ENV['ORACLE_HOST'])
  end

  context "can do a complicated join" do
    it "can join assessors table" do
      db.query("
        SELECT
          a.ACTIVE_IND, a.ASSESSOR_ID, a.BASE_POSTCODE_LOCATION, a.ADDRESS1, a.ADDRESS2, a.ADDRESS3, a.POST_TOWN,
          a.POSTCODE, a.COMPANY_NAME, a.EMAIL, a.COMPANY_FAX, a.TELEPHONE, a.COMPANY_WEBSITE, a.DATE_OF_BIRTH,
          a.FIRST_NAME, a.NAME_PREFIX, a.NAME_SUFFIX, a.SURNAME, a.DELETED_IN_UPLOAD, a.ORGANISATION_KEY,
          a.FIRST_NAME_PHONIC, a.SURNAME_PHONIC, a.ASSESSOR_LOCATION, a.MIDDLE_NAMES, a.DISPLAY_NAME, a.COMPANY_REG_NO,
          a.COMPANY_ADDR1, a.COMPANY_ADDR2, a.COMPANY_ADDR3, a.COMPANY_TOWN, a.COMPANY_POSTCODE, a.COMPANY_TELEPHONE,
          a.COMPANY_EMAIL,

          q.QUALIFICATION_STATUS_KEY, q.QUALIFICATION_TYPE_KEY,

          c.POSTCODE_COVERAGE
        FROM
          HCR.ASSESSORS a
        LEFT JOIN
          HCR.ASSESSOR_QUALIFICATIONS q ON(a.ASSESSOR_KEY = q.ASSESSOR_KEY)
        LEFT JOIN
          HCR.ASSESSOR_COVERAGE c ON(a.ASSESSOR_KEY = c.ASSESSOR_KEY)"
      )
    end

    it "can join reports table" do
      db.query("
        SELECT
          r.HCR_REPORT_KEY, r.HCR_REPORT_CODE, r.HCR_REPORT_STATUS_CODE, r.CS_CONTACT_KEY, r.INSPECTOR_CONTACT_KEY,
          r.REPORT_REFERENCE_ID, r.UNIQUE_PROPERTY_REF_NO, r.INSPECTION_DATE, r.LODGEMENT_DATE, r.REPORT_DOWNLOAD_URL,
          r.HCR_RESTRICTED_ACCESS_CODE, r.SELLER_COMMISSIONED_IND, r.CREATION_DATE, r.HCR_XSD_VERSION_KEY,
          r.REPORT_FILE_LOCATION, r.XML_FILE_LOCATION, r.STORAGE_DATE, r.CREATED_BY_CONTACT_KEY, r.LAST_UPDATE_DATE,
          r.LAST_UPDATED_BY_CONTACT_KEY, r.LANGUAGE_CODE, r.REGION_CODE, r.COUNTRY_CODE, r.ENERGY_RATING_CURRENT,
          r.ENERGY_RATING_POTENTIAL, r.CO2_EMISSIONS_CURRENT, r.CO2_EMISSIONS_POTENTIAL, r.TRANSACTION_TYPE, r.QA_DATE,
          r.SAP_XSD_VERSION_KEY, r.RDSAP_XSD_VERSION_KEY
        FROM
          HCR.HCR_REPORTS r
        LEFT JOIN

      ")
    end

    it "can join addresses table" do

    end

    it "can join contacts table" do

    end
  end
end