require "legacy"

describe "queries" do
  let(:db) do
    Legacy.new(ENV['ORACLE_USER'], ENV['ORACLE_PASSWORD'], ENV['ORACLE_HOST'])
  end

  context "can do a complicated join" do
    it "can join assessors table" do
      db.query("
        SELECT
          a.ACTIVE_IND, a.ASSESSOR_ID, a.BASE_POSTCODE_LOCATION, a.ADDRESS1, a.ADDRESS2, a.ADDRESS3, a.POST_TOWN,
          a.POSTCODE, a.COMPANY_NAME, a.EMAIL, a.COMPANY_FAX, a.TELEPHONE, a.COMPANY_WEBSITE, a.DATE_OF_BIRTH,
          a.FIRST_NAME, a.NAME_PREFIX, a.NAME_SUFFIX, a.SURNAME, a.DELETED_IN_UPLOAD, a.ORGANISATION_KEY,
          a.FIRST_NAME_PHONIC, a.SURNAME_PHONIC, a.ASSESSOR_LOCATION, a.MIDDLE_NAMES, a.DISPLAY_NAME, a.COMPANY_REG_NO,
          a.COMPANY_ADDR1, a.COMPANY_ADDR2, a.COMPANY_ADDR3, a.COMPANY_TOWN, a.COMPANY_POSTCODE, a.COMPANY_TELEPHONE,
          a.COMPANY_EMAIL,

          q.QUALIFICATION_STATUS_KEY, q.QUALIFICATION_TYPE_KEY,

          c.POSTCODE_COVERAGE
        FROM
          HCR.ASSESSORS a
        LEFT JOIN
          HCR.ASSESSOR_QUALIFICATIONS q ON(a.ASSESSOR_KEY = q.ASSESSOR_KEY)
        LEFT JOIN
          HCR.ASSESSOR_COVERAGE c ON(a.ASSESSOR_KEY = c.ASSESSOR_KEY)"
      )
    end

    it "can get reports table" do
      db.query("
        SELECT
          r.HCR_REPORT_KEY, r.HCR_REPORT_CODE, r.HCR_REPORT_STATUS_CODE, r.CS_CONTACT_KEY, r.INSPECTOR_CONTACT_KEY,
          r.REPORT_REFERENCE_ID, r.UNIQUE_PROPERTY_REF_NO, r.INSPECTION_DATE, r.LODGEMENT_DATE, r.REPORT_DOWNLOAD_URL,
          r.HCR_RESTRICTED_ACCESS_CODE, r.SELLER_COMMISSIONED_IND, r.CREATION_DATE, r.HCR_XSD_VERSION_KEY,
          r.REPORT_FILE_LOCATION, r.XML_FILE_LOCATION, r.STORAGE_DATE, r.CREATED_BY_CONTACT_KEY, r.LAST_UPDATE_DATE,
          r.LAST_UPDATED_BY_CONTACT_KEY, r.LANGUAGE_CODE, r.REGION_CODE, r.COUNTRY_CODE, r.ENERGY_RATING_CURRENT,
          r.ENERGY_RATING_POTENTIAL, r.CO2_EMISSIONS_CURRENT, r.CO2_EMISSIONS_POTENTIAL, r.TRANSACTION_TYPE, r.QA_DATE,
          r.SAP_XSD_VERSION_KEY, r.RDSAP_XSD_VERSION_KEY
        FROM
          HCR.HCR_REPORTS r
      ")

      db.query("
        SELECT
          d.HCR_REPORT_KEY, d.EPORT_FILE, d.FILE_TYLE, d.STORAGE_DATE
        FROM
          HCR.HCR_REPORT_DATA_FILES d
      ")

      db.query("
        SELECT
          f.HCR_REPORT_FILE_KEY, f.HCR_REPORT_KEY, f.HCR_FILE_CODE, f.CREATION_DATE, f.FILE_LOCATION, f.CURRENT_IND
        FROM
          HCR.HCR_REPORT_FILES f
      ")

      db.query("
        SELECT
          d.HCR_REPORT_KEY, d.CREATION_DATE, d.REPORT_PDF, d.REPORT_XML, d.STORAGE_DATE
        FROM
          HCR.HCR_REPORT_DATA d
      ")
    end

    it "can get addresses table" do
      db.query("
        SELECT
          a.UNIQUE_PROPERTY_REF_NO, a.ADDRESS_KEY, a.ORGANISATION_ID, a.DELIVERY_POINT_ID, a.ADDR_LINE_1, a.ADDR_LINE_2,
          a.ADDR_LINE_3, a.SUB_BUILDING_NAME, a.BUILDING_NAME, a.BUILDING_NUMBER, a.DEPENDANT_THOROUGHFARE_NAME,
          a.DEPENDANT_THOROUGHFARE_DESC, a.THOROUGHFARE_NAME, a.THOROUGHFARE_DESC, a.DOUBLE_DEPENDANT_LOCALITY,
          a.DEPENDANT_LOCALITY, a.POST_TOWN, a.COUNTY, a.POST_CODE, a.CREATION_DATE, a.CREATED_BY_CONTACT_KEY,
          a.LAST_UPDATE_DATE, a.LAST_UPDATED_BY_CONTACT_KEY, a.WEB_RESULTS_IND, a.NOTES, a.NEW_BUILD_IND,
          a.NEW_BUILD_HASH, a.OPT_OUT_IND, a.PERMANENT_OPT_OUT_IND
        FROM
          HCR.HCR_ADDRESSES a
      ")
    end

    it "can get contacts table" do
      db.query("
        SELECT
          c.HCR_ORGANISATION_KEY, c.HCR_CONTACT_CODE, c.HCR_CONTACT_STATUS_CODE, c.NOTIFY_LODGEMENT_IND, c.CONTACT_ID,
          c.CONTACT_PASSWORD, c.CERTIFICATE_ID, c.CERTIFICATION_DATE, c.REGISTERED_NAME, c.NAME_PREFIX, c.FIRST_NAME,
          c.SURNAME, c.NAME_SUFFIX, c.CONTACT_ADDR1, c.CONTACT_ADDR2, c.CONTACT_ADDR3, c.CONTACT_TOWN,
          c.CONTACT_COUNTY, c.CONTACT_POSTCODE, c.WEBSITE, c.EMAIL, c.TELEPHONE, c.FAX, c.QUALIFICATIONS, c.SPECIALISMS,
          c.CS_REGISTERED_NAME, c.CS_CONTACT_ADDR1, c.CS_CONTACT_ADDR2, c.CS_CONTACT_ADDR3, c.CS_CONTACT_TOWN,
          c.CS_CONTACT_POSTCODE, c.CS_WEBSITE, c.CS_EMAIL, c.CS_TELEPHONE, c.CS_FAX, c.CS_COMPLAINT_ADDR1,
          c.CS_COMPLAINT_ADDR2, c.CS_COMPLAINT_ADDR3, c.CS_COMPLAINT_TOWN, c.CS_COMPLAINT_POSTCODE,
          c.DIGITAL_CERTIFICATE, c.DELETED_IN_UPLOAD_KEY, c.CREATION_DATE, c.CREATED_BY_CONTACT_KEY, c.LAST_UPDATE_DATE,
          c.LAST_UPDATED_BY_CONTACT_KEY, c.FIRST_NAME_PHONIC, c.SURNAME_PHONIC, c.TSO_LOCAL_AUTHORITY,
          c.CERTIFICATE_GENERATION_DATE, c.ASSESSOR_LOCATION, c.BASE_LOCATION_POSTCODE, c.DATE_OF_BIRTH, c.PWD_UPD_IND,
          c.NIR_CONTACT_KEY, c.X, c.Y, c.EPC_DIGITAL_CERT, c.EPC_CERT_GENERATION_DATE, c.DIGITAL_CERTIFICATE_1024,
          c.CERT_GENERATION_DATE_1024, c.PWD_UPD_DATE
        FROM HCR.HCR_CONTACTS c
      ")
    end
  end
end